#+TITLE: Dotfiles Reloaded
#+DATE: 2017:01:25
#+AUTHOR: neymarsabin
#+EMAIL: reddevil.sabin@gmail.com

	Folder Structure:
        #+begin_example
        | /home/neymarsabin/projects/pet/dotfiles_reloaded/dots |                    |               |          |
        | ├──                                                   | doom               |               |          |
        | │                                                     | ├──                | config.el     |          |
        | │                                                     | ├──                | custom.el     |          |
        | │                                                     | ├──                | init.el       |          |
        | │                                                     | ├──                | packages.el   |          |
        | │                                                     | └──                | snippets      |          |
        | │                                                     | ├──                | go-mode       |          |
        | │                                                     | │                  | ├──           | func     |
        | │                                                     | │                  | └──           | hello    |
        | │                                                     | ├──                | org-mode      |          |
        | │                                                     | │                  | └──           | hugohead |
        | │                                                     | └──                | solidity-mode |          |
        | │                                                     | └──                | constructor   |          |
        | ├──                                                   | i3wm               |               |          |
        | │                                                     | └──                | i3            |          |
        | │                                                     | ├──                | i3blocks.conf |          |
        | │                                                     | ├──                | i3config      |          |
        | │                                                     | └──                | i3status.conf |          |
        | ├──                                                   | mplayer.conf       |               |          |
        | ├──                                                   | mplayer_input.conf |               |          |
        | ├──                                                   | tmux               |               |          |
        | └──                                                   | Xresources         |               |          |
        |                                                       |                    |               |          |
        | 8                                                     | directories,       | 15            | files    |
        #+end_example

	- *dots* -> has all the configuration for the apps I am using
	- *scripts* -> this folder makes Arch Linux usable

* How To?
- symlink essentials like ~i3config~, ~tmux~ etc into $HOME directory. I am not going to write commands to do symlinks here!!
- I am using ~Doom Emacs~, export ~$DOOMDIR~ environment variable in your .zshrc
- I recommend setting up ~.zshrc~ with ~oh-my-zsh~ if you want to have themes and plugins written and maintained by awesome people

* Laptop and OS
- Lenovo Thinkpad e14 ryzen 7 with AMD Graphics [linux works much better in AMD processors]
- Arch Linux with ~pacman~ and ~yay~ package managers

* Apps and Dependencies
- i3 window manager [ best if you are working with multiple monitors and use less mouse ]
- EMACS [ emacs-nativecomp in terminal, the GUI is not working ]
- alacritty + tmux [ alacritty has config file, tmux is awesome ]
- rofi [ replacing dmenu for everything - commands, windows, clipboard ]
- xclip and greenclip [ xclip is native clipboard manager of X11 and greenclip is too good with rofi ]
- mplayer [ I don't use this very much ]
- scrot for screenshots [ ~scrot -s <date>.png~ ]
- ranger [ terminal file manager, plus supports vim motions, but rarely use browsers ]
- firefox [ only because it has good vimium support ]

* Troubleshooting
*** Keychron K2 is not working in wired mode
**** What is the issue?
the module ~hid-apple~ was not loaded and udev rules were not triggered.

**** solution||
	- get some info on ~hid-apple~ kernel module with the help of ~modinfo~
	  #+begin_src shell
			modinfo hid-apple
	  #+end_src
	  - you will see a bunch of information displayed, if not there is something wrong

	- loading modules with ~modeprobe~
	  #+begin_src shell
			sudo modeprobe hid-apple
	  #+end_src

	- ~/sys/module/hid_apple/parameters/fnmode~ check if this file exists?
	- add ~udev~ rules to ~/etc/udev/rules.d/70-keychron.rules~
	  #+begin_src shell
			ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="05ac", ATTRS{idProduct}=="0220", RUN+="/bin/sh -c 'echo 2 > /sys/module/hid_apple/parameters/fnmode'"
	  #+end_src

**** bluetooth connection with K2 is not working yet!!!

* TODOs for fridays
- [ ] bluetooth mouse is not working, fix this for Arch Linux
- [ ] have screen tearing, I don't care much about this yet, till I get irritated
- [ ] fix EMACS GUI version
- [ ] thinkpad - tap to click is not working

