- hosts: localhost
  tasks:
    - include_vars: vars.yml
    - name: Install socials
      become: true
      pacman:
        update_cache: yes
        name:
          - firefox
          - telegram-desktop
