# setup basic packages
- hosts: localhost
  tasks:
  - include_vars: vars.yml
  - name: Install Dependencies
    become: true
    pacman:
      update_cache: yes
      name: 
        - dunst
        - fzf
        - jq
        - man
        - ripgrep
        - rofi
        - unzip
        - zip
        - xbindkeys
        - xorg-xrandr
        - arandr
        - ranger
        - openssh
        - wget
        - curl
        - libnotify
        - zathura
      state: present

  # only use this if you want to remove dependencies
  - name: Remove Dependencies
    become: true
    pacman:
      update_cache: yes
      name:
      state: absent

  - name: clone yay
    git:
      dest: "{{ workplace }}/yay"
      repo: 'https://aur.archlinux.org/yay.git'
      clone: yes
      update: yes

  - name: build yay
    args:
      chdir: "{{ workplace }}/yay/"
    command: 
      cmd: makepkg -si --noconfirm
